// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_500 from "./routes/_500.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_id_ from "./routes/api/[id].ts";
import * as $api_index from "./routes/api/index.ts";
import * as $index from "./routes/index.tsx";
import * as $new from "./routes/new.tsx";
import * as $reports_id_ from "./routes/reports/[id].tsx";
import * as $reports_index from "./routes/reports/index.tsx";
import * as $Chat from "./islands/Chat.tsx";
import * as $ReportDisplayer from "./islands/ReportDisplayer.tsx";
import * as $ReportForm from "./islands/ReportForm.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_500.tsx": $_500,
    "./routes/_app.tsx": $_app,
    "./routes/api/[id].ts": $api_id_,
    "./routes/api/index.ts": $api_index,
    "./routes/index.tsx": $index,
    "./routes/new.tsx": $new,
    "./routes/reports/[id].tsx": $reports_id_,
    "./routes/reports/index.tsx": $reports_index,
  },
  islands: {
    "./islands/Chat.tsx": $Chat,
    "./islands/ReportDisplayer.tsx": $ReportDisplayer,
    "./islands/ReportForm.tsx": $ReportForm,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
